### ISSUE TITLE
mysql no password root login not working

### ISSUE THREAD

**Issue by eternalodball** [sunny9577/proxy-scraper#6]
I edited db.js and since mysql root password was none , i left it blank and this error occured

```
[19:32:46] E/launcher - Error: /home/aao/Desktop/test/proxy-scraper/db.js:13
        password: config.,
                         ^

SyntaxError: Unexpected token ','
```

**Comment by sunny9577** [comment]
@eternalodball You can set password from config.js file, it will also allow you to set blank password as well. Just set it like this 
`config.DB_PASS = "";` 
This will allow you to connect.
